sudo: required

dist: trusty
  
language: php

php:
  - 7.0
  
addons:
  hosts:
    - localtest
    
matrix:
  fast_finish: true
    
branches:
  only:
    - master

before_script:
  - pwd
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo chmod -R 777 /var/lib/apache2/fastcgi
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - sudo adduser travis www-data
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart


script:
- sudo chmod -R 777 /home/travis/build/YetiForceCompany/apache
- curl http://127.0.0.1/test.php
- curl http://localhost/test.php
- curl http://localhost/test.php?tttt=6666
- curl http://localhost/test.php?tttt=ccccc


after_script:
- echo " ===========    /etc/apache2/conf-available    ============"
- sudo ls -all /etc/apache2/conf-available

- echo " ===========    /etc/apache2/sites-available    ============"
- sudo ls -all /etc/apache2/sites-available

- echo " ===========    /etc/apache2/mods-enabled    ============"
- sudo ls -all /etc/apache2/mods-enabled

- echo " ===========    ls -l /etc/apache2/sites-enabled/    ============"
- sudo ls -l /etc/apache2/sites-enabled/

- echo " ===========    ls -l /usr/lib/cgi-bin    ============"
- sudo ls -l /usr/lib/cgi-bin

- echo " ===========    ls -l /usr/lib/apache2/modules    ============"
- sudo ls -l /usr/lib/apache2/modules

- echo " ===========    ls -l /usr/lib/apache2    ============"
- sudo ls -l /usr/lib/apache2

- echo " ===========    ls -l /var/lib/apache2    ============"
- sudo ls -l /var/lib/apache2

- echo " ===========    /etc/apache2/sites-available/000-default.conf    ============"
- sudo cat /etc/apache2/sites-available/000-default.conf

- echo " ===========    sudo netstat -antp | grep 9000    ============"
- sudo netstat -antp | grep 9000

- echo " ===========    /etc/apache2/mods-available/fastcgi.conf    ============"
- sudo cat /etc/apache2/mods-available/fastcgi.conf

- echo " ===========    /etc/apache2/mods-available/fastcgi.load    ============"
- sudo cat /etc/apache2/mods-available/fastcgi.load

- echo " ===========    /etc/apache2/apache2.conf    ============"
- sudo cat /etc/apache2/apache2.conf

- echo " ===========    /etc/apache2/envvars    ============"
- sudo cat /etc/apache2/envvars

- echo " ===========    /etc/apache2/conf-available/php5-fpm.conf   ============"
- sudo cat /etc/apache2/conf-available/php5-fpm.conf

- echo " ===========    ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf   ============"
- sudo cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf

- echo " ===========    ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf   ============"
- sudo cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf

- echo " ===========    /var/log/apache2/error.log   ============"
- sudo cat /var/log/apache2/error.log

- echo " ===========    /var/log/apache2/access.log   ============"
- sudo cat /var/log/apache2/access.log
